# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
right_format = "$cmd_duration"

palette = "gruvbox_material_dark"

[palettes.gruvbox_material_dark]
bg0     = "#282828"
bg1     = "#32302f"
bg3     = "#45403d"

fg0     = "#d4be98"
fg1     = "#ddc7a1"
grey    = "#7c6f64"

red     = "#ea6962"
orange  = "#e78a4e"
yellow  = "#d8a657"
green   = "#a9b665"
aqua    = "#89b482"
blue    = "#7daea3"
purple  = "#d3869b"

[fill]
symbol = " "

[line_break]
disabled = true

[cmd_duration]
min_time = 2_000
style = "grey"
format = "[$duration]($style)"

[character]
success_symbol = "[(green)❯](fg1)"
error_symbol   = "[(red)❯](fg1)"
vimcmd_symbol  = "[❮](grey)"

[directory]
truncation_length = 4
truncate_to_repo = true
style = "bold blue"
read_only = " "
read_only_style = "red"

[git_branch]
style = "bold purple"
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
conflicted = "⚔️  "
ahead      = "🏎️  ×${count} "
behind     = "🐢  ×${count} "
diverged   = "🔱  🏎️  ×${ahead_count} 🐢  ×${behind_count} "
untracked  = "🛤️  ×${count} "
stashed    = "📦  "
modified   = "📝  ×${count} "
staged     = "🗃️  ×${count} "
renamed    = "📛  ×${count} "
deleted    = "🗑️  ×${count} "
style      = "orange"
format     = "$all_status$ahead_behind"

[package]
disabled = true

[cmake]
format = "[$symbol]($style)"
style = "yellow"

[rust]
format = "[$symbol]($style)"
style = "orange"

[python]
format = "[$symbol]($style)"
style = "yellow"

[nodejs]
format = "[$symbol]($style)"
style = "green"

[lua]
format = "[$symbol]($style)"
style = "blue"

